<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>	
	<Title>Generic Repository Interface and Implementation for RepoDB</Title>
    <Authors>José David Galviz Muñoz</Authors>
    <Company>Gasolutions SAS</Company>
    <Description>Interface and Implementation for a generic repository using RepoDB.</Description>
    <Copyright>Gasolutions®</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/jgalviz1974/GenericRepository.RepoDB</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<AssemblyVersion>1.0.9.3</AssemblyVersion>
    <Version>$(AssemblyVersion)</Version>
    <FileVersion>$(AssemblyVersion)</FileVersion>
	<PackageOutputPath Condition="'$(SolutionDir)' != ''">$(SolutionDir)nupkgs</PackageOutputPath>
	<PackageOutputPath Condition="'$(SolutionDir)' == ''">$(MSBuildProjectDirectory)\..\..\nupkgs</PackageOutputPath>
	<IsPackable>true</IsPackable>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<LangVersion>13.0</LangVersion>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<DocumentationFile>docs\Doc.xml</DocumentationFile>
  </PropertyGroup>

	<!-- Leer CHANGELOG.md y poblar PackageReleaseNotes antes de empaquetar -->
	<Target Name="ReadPackageReleaseNotes" BeforeTargets="GenerateNuspec;Pack">
		<ReadLinesFromFile File="$(MSBuildProjectDirectory)\CHANGELOG.md">
			<Output TaskParameter="Lines" ItemName="ReleaseNotesLines" />
		</ReadLinesFromFile>

		<PropertyGroup>
			<!-- Unir las líneas leídas en una sola propiedad separada por saltos de línea (%0A) -->
			<PackageReleaseNotes>@(ReleaseNotesLines->'%(Identity)', '%0A')</PackageReleaseNotes>
		</PropertyGroup>
	</Target>

  <ItemGroup>
    <PackageReference Include="Gasolutions.Core.GenericRepository" Version="1.0.9.3" />
    <PackageReference Include="RepoDb.SqlServer" Version="1.13.2-alpha1" />
    <PackageReference Include="RepoDb.SqlServer.BulkOperations" Version="1.13.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="readme.md">
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
